import type { Metadata } from "next"
import "./globals.css"
import Navbar from "@/components/Navbar"
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-scree text-foreground font-sans antialiased">
        <div className="relative min-h-screen bg-white flex flex-col justify-between">
          <div>
            <div>
              <Header />
            </div>
            <main className="h-[calc(100dvh-145px)] overflow-auto">
              {children}
            </main>
          </div>

          <div className="">
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  )
}
